output "state_bucket" {
  value       = aws_s3_bucket.tfstate.bucket
  description = "S3 bucket holding terraform state"
}

output "lock_table" {
  value       = aws_dynamodb_table.tflock.name
  description = "DynamoDB table used for state locking"
}

output "region" {
  value = var.region
}

output "gh_deploy_role_arn" {
  value       = try(aws_iam_role.gh_deploy[0].arn, "")
  description = "IAM role ARN that GitHub Actions assumes via OIDC (empty if github_repository unset)"
}

# Drop this snippet into environments/<env>/backend.tf to use remote state.
output "backend_config" {
  value = <<-EOT
    # Generated by infra/bootstrap. Paste into environments/<env>/backend.tf,
    # then run `terraform init -migrate-state`.
    terraform {
      backend "s3" {
        bucket         = "${aws_s3_bucket.tfstate.bucket}"
        key            = "mlops/${var.project}/<env>/terraform.tfstate"
        region         = "${var.region}"
        dynamodb_table = "${aws_dynamodb_table.tflock.name}"
        encrypt        = true
      }
    }
  EOT
}
